# Makefile.in generated by automake 1.11.6 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011 Free Software
# Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




am__make_dryrun = \
  { \
    am__dry=no; \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        echo 'am--echo: ; @echo "AM"  OK' | $(MAKE) -f - 2>/dev/null \
          | grep '^AM OK$$' >/dev/null || am__dry=yes;; \
      *) \
        for am__flg in $$MAKEFLAGS; do \
          case $$am__flg in \
            *=*|--*) ;; \
            *n*) am__dry=yes; break;; \
          esac; \
        done;; \
    esac; \
    test $$am__dry = yes; \
  }
pkgdatadir = $(datadir)/examl
pkgincludedir = $(includedir)/examl
pkglibdir = $(libdir)/examl
pkglibexecdir = $(libexecdir)/examl
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
#am__append_1 = -g3 -O0 -D_DEBUG
am__append_2 = -O2 -fomit-frame-pointer -funroll-loops
#am__append_3 = -D_HELLO
am__append_4 = -D_NOT_PRODUCTIVE
bin_PROGRAMS = exaML$(EXEEXT)
subdir = .
DIST_COMMON = $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(top_srcdir)/configure \
	$(top_srcdir)/examl/config.h.in depcomp install-sh missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = $(top_builddir)/examl/config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am_exaML_OBJECTS = axml.$(OBJEXT) \
	evaluatePartialGenericSpecial.$(OBJEXT) genericData.$(OBJEXT) \
	models.$(OBJEXT) optimizeModel.$(OBJEXT) searchAlgo.$(OBJEXT) \
	topologies.$(OBJEXT) treeIO.$(OBJEXT) \
	evaluateGenericSpecial.$(OBJEXT) faultTolerance.$(OBJEXT) \
	makenewzGenericSpecial.$(OBJEXT) \
	newviewGenericSpecial.$(OBJEXT) restartHashTable.$(OBJEXT) \
	thread.$(OBJEXT) tree.$(OBJEXT) bipartitionList.$(OBJEXT) \
	avxLikelihood.$(OBJEXT)
exaML_OBJECTS = $(am_exaML_OBJECTS)
exaML_LDADD = $(LDADD)
DEFAULT_INCLUDES = -I. -I$(top_builddir)/examl
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC    " $@;
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD  " $@;
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN   " $@;
SOURCES = $(exaML_SOURCES)
DIST_SOURCES = $(exaML_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /lhome/labererae/proj/my-ExaML/missing --run aclocal-1.11
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 0
AUTOCONF = ${SHELL} /lhome/labererae/proj/my-ExaML/missing --run autoconf
AUTOHEADER = ${SHELL} /lhome/labererae/proj/my-ExaML/missing --run autoheader
AUTOMAKE = ${SHELL} /lhome/labererae/proj/my-ExaML/missing --run automake-1.11
AWK = gawk
CC = mpicc
CCDEPMODE = depmode=gcc3

# TODO they cannot be serious with that...this is the only way of getting rid of the default -O2 -g  
CFLAGS = 
CPP = gcc -E
CPPFLAGS = 
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = -lpthread -lm 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /lhome/labererae/proj/my-ExaML/missing --run makeinfo
MKDIR_P = /bin/mkdir -p
OBJEXT = o
PACKAGE = examl
PACKAGE_BUGREPORT = bla@bla.org
PACKAGE_NAME = examl
PACKAGE_STRING = examl 1.0.1
PACKAGE_TARNAME = examl
PACKAGE_URL = 
PACKAGE_VERSION = 1.0.1
PATH_SEPARATOR = :
SET_MAKE = 
SHELL = /bin/bash
SIMD_FLAGS =  -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2
STRIP = 
VERSION = 1.0.1
abs_builddir = /lhome/labererae/proj/my-ExaML
abs_srcdir = /lhome/labererae/proj/my-ExaML
abs_top_builddir = /lhome/labererae/proj/my-ExaML
abs_top_srcdir = /lhome/labererae/proj/my-ExaML
ac_ct_CC = gcc
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /lhome/labererae/proj/my-ExaML/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
AUTOMAKE_OPTIONS = foreign
WARN_FLAGS = --pedantic -Wall #  -Wunused-parameter -Wredundant-decls  -Wreturn-type  -Wswitch-default -Wunused-value -Wimplicit  -Wimplicit-function-declaration  -Wimplicit-int -Wimport  -Wunused  -Wunused-function  -Wunused-label -Wno-int-to-pointer-cast -Wbad-function-cast -Wnested-externs  -Wold-style-definition -Wpointer-sign -Wextra -Wredundant-decls -Wunused -Wunused-function -Wunused-parameter -Wunused-value  -Wunused-variable -Wformat  -Wformat-nonliteral -Wparentheses -Wsequence-point -Wuninitialized -Wundef -Wbad-function-cast #   -Wstrict-prototypes   -Wdeclaration-after-statement  -Wmissing-prototypes  
LANG_FLAGS = -std=gnu99 # because of asm 
CXXFLAGS = 
FEATURE_FLAGS = -D_USE_ALLREDUCE -D_HYBRID
AM_CFLAGS = -D__SIM_SSE3 -msse3 -D_GNU_SOURCE -D_OPTIMIZED_FUNCTIONS \
	$(am__append_1) $(am__append_2) $(am__append_3) \
	$(am__append_4) $(FEATURE_FLAGS) $(WARN_FLAGS) $(LANG_FLAGS)
AM_CXXFLAGS = $(AM_CFLAGS)
AM_LDFLAGS = -lm
exaML_SOURCES = examl/axml.c  examl/evaluatePartialGenericSpecial.c examl/genericData.c examl/models.c examl/optimizeModel.c examl/searchAlgo.c examl/topologies.c examl/treeIO.c  examl/evaluateGenericSpecial.c  examl/faultTolerance.c examl/makenewzGenericSpecial.c examl/newviewGenericSpecial.c examl/restartHashTable.c examl/thread.c examl/tree.c examl/bipartitionList.c examl/avxLikelihood.c
all: all-am

.SUFFIXES:
.SUFFIXES: .c .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

examl/config.h: examl/stamp-h1
	@if test ! -f $@; then rm -f examl/stamp-h1; else :; fi
	@if test ! -f $@; then $(MAKE) $(AM_MAKEFLAGS) examl/stamp-h1; else :; fi

examl/stamp-h1: $(top_srcdir)/examl/config.h.in $(top_builddir)/config.status
	@rm -f examl/stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status examl/config.h
$(top_srcdir)/examl/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f examl/stamp-h1
	touch $@

distclean-hdr:
	-rm -f examl/config.h examl/stamp-h1
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p; \
	  then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' `; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
exaML$(EXEEXT): $(exaML_OBJECTS) $(exaML_DEPENDENCIES) $(EXTRA_exaML_DEPENDENCIES) 
	@rm -f exaML$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(exaML_OBJECTS) $(exaML_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/avxLikelihood.Po
include ./$(DEPDIR)/axml.Po
include ./$(DEPDIR)/bipartitionList.Po
include ./$(DEPDIR)/evaluateGenericSpecial.Po
include ./$(DEPDIR)/evaluatePartialGenericSpecial.Po
include ./$(DEPDIR)/faultTolerance.Po
include ./$(DEPDIR)/genericData.Po
include ./$(DEPDIR)/makenewzGenericSpecial.Po
include ./$(DEPDIR)/models.Po
include ./$(DEPDIR)/newviewGenericSpecial.Po
include ./$(DEPDIR)/optimizeModel.Po
include ./$(DEPDIR)/restartHashTable.Po
include ./$(DEPDIR)/searchAlgo.Po
include ./$(DEPDIR)/thread.Po
include ./$(DEPDIR)/topologies.Po
include ./$(DEPDIR)/tree.Po
include ./$(DEPDIR)/treeIO.Po

.c.o:
	$(AM_V_CC)$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c $<

.c.obj:
	$(AM_V_CC)$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c `$(CYGPATH_W) '$<'`

axml.o: examl/axml.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT axml.o -MD -MP -MF $(DEPDIR)/axml.Tpo -c -o axml.o `test -f 'examl/axml.c' || echo '$(srcdir)/'`examl/axml.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/axml.Tpo $(DEPDIR)/axml.Po
#	$(AM_V_CC)source='examl/axml.c' object='axml.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o axml.o `test -f 'examl/axml.c' || echo '$(srcdir)/'`examl/axml.c

axml.obj: examl/axml.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT axml.obj -MD -MP -MF $(DEPDIR)/axml.Tpo -c -o axml.obj `if test -f 'examl/axml.c'; then $(CYGPATH_W) 'examl/axml.c'; else $(CYGPATH_W) '$(srcdir)/examl/axml.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/axml.Tpo $(DEPDIR)/axml.Po
#	$(AM_V_CC)source='examl/axml.c' object='axml.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o axml.obj `if test -f 'examl/axml.c'; then $(CYGPATH_W) 'examl/axml.c'; else $(CYGPATH_W) '$(srcdir)/examl/axml.c'; fi`

evaluatePartialGenericSpecial.o: examl/evaluatePartialGenericSpecial.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT evaluatePartialGenericSpecial.o -MD -MP -MF $(DEPDIR)/evaluatePartialGenericSpecial.Tpo -c -o evaluatePartialGenericSpecial.o `test -f 'examl/evaluatePartialGenericSpecial.c' || echo '$(srcdir)/'`examl/evaluatePartialGenericSpecial.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/evaluatePartialGenericSpecial.Tpo $(DEPDIR)/evaluatePartialGenericSpecial.Po
#	$(AM_V_CC)source='examl/evaluatePartialGenericSpecial.c' object='evaluatePartialGenericSpecial.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o evaluatePartialGenericSpecial.o `test -f 'examl/evaluatePartialGenericSpecial.c' || echo '$(srcdir)/'`examl/evaluatePartialGenericSpecial.c

evaluatePartialGenericSpecial.obj: examl/evaluatePartialGenericSpecial.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT evaluatePartialGenericSpecial.obj -MD -MP -MF $(DEPDIR)/evaluatePartialGenericSpecial.Tpo -c -o evaluatePartialGenericSpecial.obj `if test -f 'examl/evaluatePartialGenericSpecial.c'; then $(CYGPATH_W) 'examl/evaluatePartialGenericSpecial.c'; else $(CYGPATH_W) '$(srcdir)/examl/evaluatePartialGenericSpecial.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/evaluatePartialGenericSpecial.Tpo $(DEPDIR)/evaluatePartialGenericSpecial.Po
#	$(AM_V_CC)source='examl/evaluatePartialGenericSpecial.c' object='evaluatePartialGenericSpecial.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o evaluatePartialGenericSpecial.obj `if test -f 'examl/evaluatePartialGenericSpecial.c'; then $(CYGPATH_W) 'examl/evaluatePartialGenericSpecial.c'; else $(CYGPATH_W) '$(srcdir)/examl/evaluatePartialGenericSpecial.c'; fi`

genericData.o: examl/genericData.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT genericData.o -MD -MP -MF $(DEPDIR)/genericData.Tpo -c -o genericData.o `test -f 'examl/genericData.c' || echo '$(srcdir)/'`examl/genericData.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/genericData.Tpo $(DEPDIR)/genericData.Po
#	$(AM_V_CC)source='examl/genericData.c' object='genericData.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o genericData.o `test -f 'examl/genericData.c' || echo '$(srcdir)/'`examl/genericData.c

genericData.obj: examl/genericData.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT genericData.obj -MD -MP -MF $(DEPDIR)/genericData.Tpo -c -o genericData.obj `if test -f 'examl/genericData.c'; then $(CYGPATH_W) 'examl/genericData.c'; else $(CYGPATH_W) '$(srcdir)/examl/genericData.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/genericData.Tpo $(DEPDIR)/genericData.Po
#	$(AM_V_CC)source='examl/genericData.c' object='genericData.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o genericData.obj `if test -f 'examl/genericData.c'; then $(CYGPATH_W) 'examl/genericData.c'; else $(CYGPATH_W) '$(srcdir)/examl/genericData.c'; fi`

models.o: examl/models.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT models.o -MD -MP -MF $(DEPDIR)/models.Tpo -c -o models.o `test -f 'examl/models.c' || echo '$(srcdir)/'`examl/models.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/models.Tpo $(DEPDIR)/models.Po
#	$(AM_V_CC)source='examl/models.c' object='models.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o models.o `test -f 'examl/models.c' || echo '$(srcdir)/'`examl/models.c

models.obj: examl/models.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT models.obj -MD -MP -MF $(DEPDIR)/models.Tpo -c -o models.obj `if test -f 'examl/models.c'; then $(CYGPATH_W) 'examl/models.c'; else $(CYGPATH_W) '$(srcdir)/examl/models.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/models.Tpo $(DEPDIR)/models.Po
#	$(AM_V_CC)source='examl/models.c' object='models.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o models.obj `if test -f 'examl/models.c'; then $(CYGPATH_W) 'examl/models.c'; else $(CYGPATH_W) '$(srcdir)/examl/models.c'; fi`

optimizeModel.o: examl/optimizeModel.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT optimizeModel.o -MD -MP -MF $(DEPDIR)/optimizeModel.Tpo -c -o optimizeModel.o `test -f 'examl/optimizeModel.c' || echo '$(srcdir)/'`examl/optimizeModel.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/optimizeModel.Tpo $(DEPDIR)/optimizeModel.Po
#	$(AM_V_CC)source='examl/optimizeModel.c' object='optimizeModel.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o optimizeModel.o `test -f 'examl/optimizeModel.c' || echo '$(srcdir)/'`examl/optimizeModel.c

optimizeModel.obj: examl/optimizeModel.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT optimizeModel.obj -MD -MP -MF $(DEPDIR)/optimizeModel.Tpo -c -o optimizeModel.obj `if test -f 'examl/optimizeModel.c'; then $(CYGPATH_W) 'examl/optimizeModel.c'; else $(CYGPATH_W) '$(srcdir)/examl/optimizeModel.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/optimizeModel.Tpo $(DEPDIR)/optimizeModel.Po
#	$(AM_V_CC)source='examl/optimizeModel.c' object='optimizeModel.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o optimizeModel.obj `if test -f 'examl/optimizeModel.c'; then $(CYGPATH_W) 'examl/optimizeModel.c'; else $(CYGPATH_W) '$(srcdir)/examl/optimizeModel.c'; fi`

searchAlgo.o: examl/searchAlgo.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT searchAlgo.o -MD -MP -MF $(DEPDIR)/searchAlgo.Tpo -c -o searchAlgo.o `test -f 'examl/searchAlgo.c' || echo '$(srcdir)/'`examl/searchAlgo.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/searchAlgo.Tpo $(DEPDIR)/searchAlgo.Po
#	$(AM_V_CC)source='examl/searchAlgo.c' object='searchAlgo.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o searchAlgo.o `test -f 'examl/searchAlgo.c' || echo '$(srcdir)/'`examl/searchAlgo.c

searchAlgo.obj: examl/searchAlgo.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT searchAlgo.obj -MD -MP -MF $(DEPDIR)/searchAlgo.Tpo -c -o searchAlgo.obj `if test -f 'examl/searchAlgo.c'; then $(CYGPATH_W) 'examl/searchAlgo.c'; else $(CYGPATH_W) '$(srcdir)/examl/searchAlgo.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/searchAlgo.Tpo $(DEPDIR)/searchAlgo.Po
#	$(AM_V_CC)source='examl/searchAlgo.c' object='searchAlgo.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o searchAlgo.obj `if test -f 'examl/searchAlgo.c'; then $(CYGPATH_W) 'examl/searchAlgo.c'; else $(CYGPATH_W) '$(srcdir)/examl/searchAlgo.c'; fi`

topologies.o: examl/topologies.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT topologies.o -MD -MP -MF $(DEPDIR)/topologies.Tpo -c -o topologies.o `test -f 'examl/topologies.c' || echo '$(srcdir)/'`examl/topologies.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/topologies.Tpo $(DEPDIR)/topologies.Po
#	$(AM_V_CC)source='examl/topologies.c' object='topologies.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o topologies.o `test -f 'examl/topologies.c' || echo '$(srcdir)/'`examl/topologies.c

topologies.obj: examl/topologies.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT topologies.obj -MD -MP -MF $(DEPDIR)/topologies.Tpo -c -o topologies.obj `if test -f 'examl/topologies.c'; then $(CYGPATH_W) 'examl/topologies.c'; else $(CYGPATH_W) '$(srcdir)/examl/topologies.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/topologies.Tpo $(DEPDIR)/topologies.Po
#	$(AM_V_CC)source='examl/topologies.c' object='topologies.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o topologies.obj `if test -f 'examl/topologies.c'; then $(CYGPATH_W) 'examl/topologies.c'; else $(CYGPATH_W) '$(srcdir)/examl/topologies.c'; fi`

treeIO.o: examl/treeIO.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT treeIO.o -MD -MP -MF $(DEPDIR)/treeIO.Tpo -c -o treeIO.o `test -f 'examl/treeIO.c' || echo '$(srcdir)/'`examl/treeIO.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/treeIO.Tpo $(DEPDIR)/treeIO.Po
#	$(AM_V_CC)source='examl/treeIO.c' object='treeIO.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o treeIO.o `test -f 'examl/treeIO.c' || echo '$(srcdir)/'`examl/treeIO.c

treeIO.obj: examl/treeIO.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT treeIO.obj -MD -MP -MF $(DEPDIR)/treeIO.Tpo -c -o treeIO.obj `if test -f 'examl/treeIO.c'; then $(CYGPATH_W) 'examl/treeIO.c'; else $(CYGPATH_W) '$(srcdir)/examl/treeIO.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/treeIO.Tpo $(DEPDIR)/treeIO.Po
#	$(AM_V_CC)source='examl/treeIO.c' object='treeIO.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o treeIO.obj `if test -f 'examl/treeIO.c'; then $(CYGPATH_W) 'examl/treeIO.c'; else $(CYGPATH_W) '$(srcdir)/examl/treeIO.c'; fi`

evaluateGenericSpecial.o: examl/evaluateGenericSpecial.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT evaluateGenericSpecial.o -MD -MP -MF $(DEPDIR)/evaluateGenericSpecial.Tpo -c -o evaluateGenericSpecial.o `test -f 'examl/evaluateGenericSpecial.c' || echo '$(srcdir)/'`examl/evaluateGenericSpecial.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/evaluateGenericSpecial.Tpo $(DEPDIR)/evaluateGenericSpecial.Po
#	$(AM_V_CC)source='examl/evaluateGenericSpecial.c' object='evaluateGenericSpecial.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o evaluateGenericSpecial.o `test -f 'examl/evaluateGenericSpecial.c' || echo '$(srcdir)/'`examl/evaluateGenericSpecial.c

evaluateGenericSpecial.obj: examl/evaluateGenericSpecial.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT evaluateGenericSpecial.obj -MD -MP -MF $(DEPDIR)/evaluateGenericSpecial.Tpo -c -o evaluateGenericSpecial.obj `if test -f 'examl/evaluateGenericSpecial.c'; then $(CYGPATH_W) 'examl/evaluateGenericSpecial.c'; else $(CYGPATH_W) '$(srcdir)/examl/evaluateGenericSpecial.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/evaluateGenericSpecial.Tpo $(DEPDIR)/evaluateGenericSpecial.Po
#	$(AM_V_CC)source='examl/evaluateGenericSpecial.c' object='evaluateGenericSpecial.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o evaluateGenericSpecial.obj `if test -f 'examl/evaluateGenericSpecial.c'; then $(CYGPATH_W) 'examl/evaluateGenericSpecial.c'; else $(CYGPATH_W) '$(srcdir)/examl/evaluateGenericSpecial.c'; fi`

faultTolerance.o: examl/faultTolerance.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT faultTolerance.o -MD -MP -MF $(DEPDIR)/faultTolerance.Tpo -c -o faultTolerance.o `test -f 'examl/faultTolerance.c' || echo '$(srcdir)/'`examl/faultTolerance.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/faultTolerance.Tpo $(DEPDIR)/faultTolerance.Po
#	$(AM_V_CC)source='examl/faultTolerance.c' object='faultTolerance.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o faultTolerance.o `test -f 'examl/faultTolerance.c' || echo '$(srcdir)/'`examl/faultTolerance.c

faultTolerance.obj: examl/faultTolerance.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT faultTolerance.obj -MD -MP -MF $(DEPDIR)/faultTolerance.Tpo -c -o faultTolerance.obj `if test -f 'examl/faultTolerance.c'; then $(CYGPATH_W) 'examl/faultTolerance.c'; else $(CYGPATH_W) '$(srcdir)/examl/faultTolerance.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/faultTolerance.Tpo $(DEPDIR)/faultTolerance.Po
#	$(AM_V_CC)source='examl/faultTolerance.c' object='faultTolerance.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o faultTolerance.obj `if test -f 'examl/faultTolerance.c'; then $(CYGPATH_W) 'examl/faultTolerance.c'; else $(CYGPATH_W) '$(srcdir)/examl/faultTolerance.c'; fi`

makenewzGenericSpecial.o: examl/makenewzGenericSpecial.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT makenewzGenericSpecial.o -MD -MP -MF $(DEPDIR)/makenewzGenericSpecial.Tpo -c -o makenewzGenericSpecial.o `test -f 'examl/makenewzGenericSpecial.c' || echo '$(srcdir)/'`examl/makenewzGenericSpecial.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/makenewzGenericSpecial.Tpo $(DEPDIR)/makenewzGenericSpecial.Po
#	$(AM_V_CC)source='examl/makenewzGenericSpecial.c' object='makenewzGenericSpecial.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o makenewzGenericSpecial.o `test -f 'examl/makenewzGenericSpecial.c' || echo '$(srcdir)/'`examl/makenewzGenericSpecial.c

makenewzGenericSpecial.obj: examl/makenewzGenericSpecial.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT makenewzGenericSpecial.obj -MD -MP -MF $(DEPDIR)/makenewzGenericSpecial.Tpo -c -o makenewzGenericSpecial.obj `if test -f 'examl/makenewzGenericSpecial.c'; then $(CYGPATH_W) 'examl/makenewzGenericSpecial.c'; else $(CYGPATH_W) '$(srcdir)/examl/makenewzGenericSpecial.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/makenewzGenericSpecial.Tpo $(DEPDIR)/makenewzGenericSpecial.Po
#	$(AM_V_CC)source='examl/makenewzGenericSpecial.c' object='makenewzGenericSpecial.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o makenewzGenericSpecial.obj `if test -f 'examl/makenewzGenericSpecial.c'; then $(CYGPATH_W) 'examl/makenewzGenericSpecial.c'; else $(CYGPATH_W) '$(srcdir)/examl/makenewzGenericSpecial.c'; fi`

newviewGenericSpecial.o: examl/newviewGenericSpecial.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT newviewGenericSpecial.o -MD -MP -MF $(DEPDIR)/newviewGenericSpecial.Tpo -c -o newviewGenericSpecial.o `test -f 'examl/newviewGenericSpecial.c' || echo '$(srcdir)/'`examl/newviewGenericSpecial.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/newviewGenericSpecial.Tpo $(DEPDIR)/newviewGenericSpecial.Po
#	$(AM_V_CC)source='examl/newviewGenericSpecial.c' object='newviewGenericSpecial.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o newviewGenericSpecial.o `test -f 'examl/newviewGenericSpecial.c' || echo '$(srcdir)/'`examl/newviewGenericSpecial.c

newviewGenericSpecial.obj: examl/newviewGenericSpecial.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT newviewGenericSpecial.obj -MD -MP -MF $(DEPDIR)/newviewGenericSpecial.Tpo -c -o newviewGenericSpecial.obj `if test -f 'examl/newviewGenericSpecial.c'; then $(CYGPATH_W) 'examl/newviewGenericSpecial.c'; else $(CYGPATH_W) '$(srcdir)/examl/newviewGenericSpecial.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/newviewGenericSpecial.Tpo $(DEPDIR)/newviewGenericSpecial.Po
#	$(AM_V_CC)source='examl/newviewGenericSpecial.c' object='newviewGenericSpecial.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o newviewGenericSpecial.obj `if test -f 'examl/newviewGenericSpecial.c'; then $(CYGPATH_W) 'examl/newviewGenericSpecial.c'; else $(CYGPATH_W) '$(srcdir)/examl/newviewGenericSpecial.c'; fi`

restartHashTable.o: examl/restartHashTable.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT restartHashTable.o -MD -MP -MF $(DEPDIR)/restartHashTable.Tpo -c -o restartHashTable.o `test -f 'examl/restartHashTable.c' || echo '$(srcdir)/'`examl/restartHashTable.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/restartHashTable.Tpo $(DEPDIR)/restartHashTable.Po
#	$(AM_V_CC)source='examl/restartHashTable.c' object='restartHashTable.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o restartHashTable.o `test -f 'examl/restartHashTable.c' || echo '$(srcdir)/'`examl/restartHashTable.c

restartHashTable.obj: examl/restartHashTable.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT restartHashTable.obj -MD -MP -MF $(DEPDIR)/restartHashTable.Tpo -c -o restartHashTable.obj `if test -f 'examl/restartHashTable.c'; then $(CYGPATH_W) 'examl/restartHashTable.c'; else $(CYGPATH_W) '$(srcdir)/examl/restartHashTable.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/restartHashTable.Tpo $(DEPDIR)/restartHashTable.Po
#	$(AM_V_CC)source='examl/restartHashTable.c' object='restartHashTable.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o restartHashTable.obj `if test -f 'examl/restartHashTable.c'; then $(CYGPATH_W) 'examl/restartHashTable.c'; else $(CYGPATH_W) '$(srcdir)/examl/restartHashTable.c'; fi`

thread.o: examl/thread.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT thread.o -MD -MP -MF $(DEPDIR)/thread.Tpo -c -o thread.o `test -f 'examl/thread.c' || echo '$(srcdir)/'`examl/thread.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/thread.Tpo $(DEPDIR)/thread.Po
#	$(AM_V_CC)source='examl/thread.c' object='thread.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o thread.o `test -f 'examl/thread.c' || echo '$(srcdir)/'`examl/thread.c

thread.obj: examl/thread.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT thread.obj -MD -MP -MF $(DEPDIR)/thread.Tpo -c -o thread.obj `if test -f 'examl/thread.c'; then $(CYGPATH_W) 'examl/thread.c'; else $(CYGPATH_W) '$(srcdir)/examl/thread.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/thread.Tpo $(DEPDIR)/thread.Po
#	$(AM_V_CC)source='examl/thread.c' object='thread.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o thread.obj `if test -f 'examl/thread.c'; then $(CYGPATH_W) 'examl/thread.c'; else $(CYGPATH_W) '$(srcdir)/examl/thread.c'; fi`

tree.o: examl/tree.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT tree.o -MD -MP -MF $(DEPDIR)/tree.Tpo -c -o tree.o `test -f 'examl/tree.c' || echo '$(srcdir)/'`examl/tree.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/tree.Tpo $(DEPDIR)/tree.Po
#	$(AM_V_CC)source='examl/tree.c' object='tree.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o tree.o `test -f 'examl/tree.c' || echo '$(srcdir)/'`examl/tree.c

tree.obj: examl/tree.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT tree.obj -MD -MP -MF $(DEPDIR)/tree.Tpo -c -o tree.obj `if test -f 'examl/tree.c'; then $(CYGPATH_W) 'examl/tree.c'; else $(CYGPATH_W) '$(srcdir)/examl/tree.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/tree.Tpo $(DEPDIR)/tree.Po
#	$(AM_V_CC)source='examl/tree.c' object='tree.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o tree.obj `if test -f 'examl/tree.c'; then $(CYGPATH_W) 'examl/tree.c'; else $(CYGPATH_W) '$(srcdir)/examl/tree.c'; fi`

bipartitionList.o: examl/bipartitionList.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT bipartitionList.o -MD -MP -MF $(DEPDIR)/bipartitionList.Tpo -c -o bipartitionList.o `test -f 'examl/bipartitionList.c' || echo '$(srcdir)/'`examl/bipartitionList.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/bipartitionList.Tpo $(DEPDIR)/bipartitionList.Po
#	$(AM_V_CC)source='examl/bipartitionList.c' object='bipartitionList.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o bipartitionList.o `test -f 'examl/bipartitionList.c' || echo '$(srcdir)/'`examl/bipartitionList.c

bipartitionList.obj: examl/bipartitionList.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT bipartitionList.obj -MD -MP -MF $(DEPDIR)/bipartitionList.Tpo -c -o bipartitionList.obj `if test -f 'examl/bipartitionList.c'; then $(CYGPATH_W) 'examl/bipartitionList.c'; else $(CYGPATH_W) '$(srcdir)/examl/bipartitionList.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bipartitionList.Tpo $(DEPDIR)/bipartitionList.Po
#	$(AM_V_CC)source='examl/bipartitionList.c' object='bipartitionList.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o bipartitionList.obj `if test -f 'examl/bipartitionList.c'; then $(CYGPATH_W) 'examl/bipartitionList.c'; else $(CYGPATH_W) '$(srcdir)/examl/bipartitionList.c'; fi`

avxLikelihood.o: examl/avxLikelihood.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT avxLikelihood.o -MD -MP -MF $(DEPDIR)/avxLikelihood.Tpo -c -o avxLikelihood.o `test -f 'examl/avxLikelihood.c' || echo '$(srcdir)/'`examl/avxLikelihood.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/avxLikelihood.Tpo $(DEPDIR)/avxLikelihood.Po
#	$(AM_V_CC)source='examl/avxLikelihood.c' object='avxLikelihood.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o avxLikelihood.o `test -f 'examl/avxLikelihood.c' || echo '$(srcdir)/'`examl/avxLikelihood.c

avxLikelihood.obj: examl/avxLikelihood.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT avxLikelihood.obj -MD -MP -MF $(DEPDIR)/avxLikelihood.Tpo -c -o avxLikelihood.obj `if test -f 'examl/avxLikelihood.c'; then $(CYGPATH_W) 'examl/avxLikelihood.c'; else $(CYGPATH_W) '$(srcdir)/examl/avxLikelihood.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/avxLikelihood.Tpo $(DEPDIR)/avxLikelihood.Po
#	$(AM_V_CC)source='examl/avxLikelihood.c' object='avxLikelihood.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o avxLikelihood.obj `if test -f 'examl/avxLikelihood.c'; then $(CYGPATH_W) 'examl/avxLikelihood.c'; else $(CYGPATH_W) '$(srcdir)/examl/avxLikelihood.c'; fi`

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  lzma -dc $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod u+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS)
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-generic ctags dist dist-all dist-bzip2 \
	dist-gzip dist-lzip dist-lzma dist-shar dist-tarZ dist-xz \
	dist-zip distcheck distclean distclean-compile \
	distclean-generic distclean-hdr distclean-tags distcleancheck \
	distdir distuninstallcheck dvi dvi-am html html-am info \
	info-am install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags uninstall \
	uninstall-am uninstall-binPROGRAMS


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
